youjiao/book/models.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from youjiao.extensions import db
from youjiao.utils.database import CRUDMixin
import sqlalchemy as sqla
from sqlalchemy.dialects.postgresql import ARRAY
from youjiao.user_util.models import Comment
from flask import url_for


class Book(db.Model, CRUDMixin):
    id = sqla.Column(sqla.Integer, primary_key=True)
    name = db.Column(sqla.String(50))
    chief_editor = db.Column(sqla.String(16))
    executive_editor = db.Column(sqla.String(16))
    publisher = db.Column(sqla.String(16))
    book_size = db.Column(sqla.Enum(u'16开', name='book_size'))
    level = db.Column(sqla.Enum(u'小班', u'中班', u'大班', name='level'))
    category = db.Column(sqla.Enum(u'幼教教材', u'幼教读物', name='book_category'))
    price = db.Column(sqla.Numeric(10, 2), default=30)
    publish = db.Column(sqla.Boolean, default=False)
    image_array = db.Column(ARRAY(sqla.String(255)))
    preview_array = db.Column(ARRAY(sqla.String(255)))

    @classmethod
    def read_book_top10(cls):
        return cls.query.filter_by(category=u'幼教读物').limit(10)

    @classmethod
    def teach_book_tol10(cls):
        return cls.query.filter_by(category=u'幼教教材').limit(10)

    @classmethod
    def top10(cls):
        return cls.query.limit(10)

    @property
    def cover(self):
        if len(self.image_array) == 0:
            return 'http://7xj2zj.com2.z0.glb.qiniucdn.com/1.jpg'
        else:
            return self.image_array[0]

    @property
    def link(self):
        return url_for('book_view.book_detail', book_id=self.id)

    def comment(self, page=0):
        return Comment.query.filter_by(comment_obj_type='book').filter_by(comment_obj_id=self.id)

youjiao/onlinecourse/models.py
# -*- coding: utf-8 -*-
from youjiao.extensions import db, redis_cli
from youjiao.utils.database import CRUDMixin, CreateUpdateTimeMixin
from youjiao.flask_qiniu import get_private_url
import sqlalchemy as sqla
from flask import url_for
from sqlalchemy.dialects.postgresql import JSON


class OnlineCourse(CRUDMixin, CreateUpdateTimeMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    publish = db.Column(sqla.Boolean, default=False)
    name = db.Column(sqla.String(200))
    url = db.Column(sqla.String(200))
    category = db.Column(
        sqla.Enum(u'优秀课堂', u'优秀讲座', u'其他视频', u'产品使用培训', u'师资培训视频',
                  name='online_course_category'))
    content = db.Column(JSON)

    @classmethod
    def get_category(cls, category):
        return cls.query.filter_by(category=category, publish=True)

    @property
    def link(self):
        return url_for('online_course.video_detail', video_id=self.id)

    @property
    def cover(self):
        if self.content.get('full_video'):
            video_cover = self.content['full_video'] + '?vframe/jpg/offset/7/w/480/h/360'
            return get_private_url(video_cover)
        return 'http://7xn3in.com2.z0.glb.qiniucdn.com/logo-big.jpg'

    def add_user_visit_recent(self, user):
        key = user.onlinecourse_visit_recent_key
        redis_cli.lpush(key, self.id)
        redis_cli.ltrim(key, 0, 8)

    @classmethod
    def top10(cls):
        return cls.query.filter(cls.publish==True).limit(10)

youjiao/__init__.py
__author__ = 'x'

from .app import create_app

youjiao/app.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from flask_admin import Admin
from flask import Flask, render_template
from flask_wtf import CsrfProtect
from flask_babelex import Babel
from flask_principal import Principal, identity_loaded
from flask_debugtoolbar import DebugToolbarExtension

# from .config import Config
from . import config as youjiao_config
from .user.utils import load_user
from .user.subscribers import connect as user_connect
from .extensions import db, limiter, admin, redis_cli, flask_qiniu, jwt, \
    login_manager
from .utils.csrf import check_csrf

# user
from .user.models import User
from .user.admin import UserAdmin
from .user.utils import _on_identity_loaded
from .user.views import user_bp
from .user.api import user_api_bp

# content
from .content.admin import ActivityAdmin
from .content.models import Activity, Slider, ContentList
from .content.views import content_bp

# book
from .teach_material.admin import BookAdmin
from .teach_material.models import Book, Courseware
from .teach_material.views import book_bp
from .teach_material.api import book_api_bp

# user util
from .user_util.models import Favor
from .user_util.api import user_util_api_bp
from .user_util.admin import LeaveMessageAdmin

# photo
from .photo.models import Photo, Album
from .photo.admin import AlbumAdmin

# yj_media
from .yj_media.admin import VideoAdmin
from .yj_media.models import Video, Audio, Document
from .yj_media.views import media_bp

# online course
from .onlinecourse.models import OnlineCourse
from .onlinecourse.views import online_course_bp
from .onlinecourse.admin import OnlineCourseAdmin

import os
import json


# Flask views
def index():
    # import ipdb; ipdb.set_trace()
    book_content_list = ContentList.query.filter(
        ContentList.position==ContentList.HOME_BOOK).first()
    if book_content_list:
        book_list = book_content_list.obj_list
    else:
        book_list = Book.top10()

    courseware_content_list = ContentList.query.filter(
        ContentList.position==ContentList.HOME_COURSEWARE).first()
    if courseware_content_list:
        courseware_list = courseware_content_list.obj_list
    else:
        courseware_list = Courseware.top10()

    onlinecourse_content_list = ContentList.query.filter(
        ContentList.position==u'首页视频').first()
    if onlinecourse_content_list:
        onlinecourse_list = onlinecourse_content_list.obj_list
    else:
        onlinecourse_list = OnlineCourse.top10()
    return render_template('home/home.html', current_page='home',
                           Book=Book, Courseware=Courseware,
                           slider=Slider.home_slider(),
                           book_list=book_list, courseware_list=courseware_list,
                           onlinecourse_list=onlinecourse_list)


def create_app():
    app = Flask(__name__)
    app.config.from_object(youjiao_config)

    # flask_sqlalchemy
    # import ipdb; ipdb.set_trace()
    db.init_app(app)

    # flask_redis
    redis_cli.init_app(app)



    # flask_debug
    if app.config.get('DEBUG'):
        DebugToolbarExtension(app)

    # flask_login
    login_manager.user_loader(load_user)
    login_manager.login_view = 'user_view.login'
    login_manager.init_app(app)

    # flask_jwt
    jwt.init_app(app)

    # flask_principal
    Principal(app)
    identity_loaded.connect_via(app)(_on_identity_loaded)

    # flask_wtf csrf
    csrf = CsrfProtect()
    csrf.init_app(app)
    app.before_request(check_csrf(csrf))

    # flask_babel
    Babel(app)

    # flask_limiter
    limiter.init_app(app)

    # flask_qiniu
    flask_qiniu.init_app(app)

    # flask_admin
    admin.init_app(app)

    # register blueprint
    app.register_blueprint(content_bp)

    app.register_blueprint(user_bp)

    app.register_blueprint(user_api_bp)

    # import ipdb; ipdb.set_trace()
    app.register_blueprint(book_bp)
    app.register_blueprint(book_api_bp)
    app.register_blueprint(user_util_api_bp)
    app.register_blueprint(media_bp)
    app.register_blueprint(online_course_bp)

    # register subscriber
    user_connect(app)

    # register home page
    app.add_url_rule('/', 'index', index)

    with open(os.path.join(os.getcwd(), 'youjiao/static/assets.json.py'), 'r') as assets:
        app.assets = json.load(assets)

    return app

youjiao/book/views.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from flask import Blueprint, render_template, abort
from youjiao.user_util.models import Comment
from sqlalchemy import and_
from .models import Book

book_bp = Blueprint("book_view", __name__)


@book_bp.route('/book')
def book():
    teach_book_list = Book.query.filter_by(category=u'幼教教材').limit(9)
    read_book_list = Book.query.filter_by(category=u'幼教读物').limit(9)
    # import ipdb; ipdb.set_trace()
    return render_template('book/home.html', teach_book_list=teach_book_list,
                           read_book_list=read_book_list, Book=Book)


@book_bp.route('/book/upload')
def book_upload():
    return render_template('book/upload.html')


@book_bp.route('/book/<category>')
def book_category(category):
    if category == 'teach_book':
        book_list = Book.query.filter_by(category=u'幼教教材').limit(9)
        top10 = Book.top10()
        return render_template('book/sub_node.html', book_list=book_list, top10=top10)

    elif category == 'read_book':
        book_list = Book.query.filter_by(category=u'幼教读物').limit(9)
        return render_template('book/sub_node.html', book_list=book_list)
    else:
        abort(404)


@book_bp.route('/book/<int:book_id>')
def book_detail(book_id):
    book = Book.query.get_or_404(book_id)
    page_comment = Comment.query.filter(
        and_(Comment.comment_obj_type == 'book',
             Comment.comment_obj_id == book.id)).paginate(1)
    return render_template('book/detail.html', book=book,
                           page_comment=page_comment)

youjiao/config/__init__.py
from __future__ import absolute_import
from datetime import timedelta

# Create dummy secrey key so we can use sessions
SECRET_KEY = '123456790'

# DEBUG
DEBUG = True

# Create in-memory database
SQLALCHEMY_DATABASE_URI = 'postgresql://youjiao_db_admin:123@localhost/youjiao_db'
SQLALCHEMY_ECHO = True

# for user register and login security
PASSWORD_HASH = "pbkdf2_sha512"
PASSWORD_SALT = "W0dRBgO0Ukobw8NweLAXvqug2ZTh97HZIEMFcEsWhf7lt68"

# flask_wtf
WTF_CSRF_CHECK_DEFAULT = False

# flask_babel
BABEL_DEFAULT_LOCALE = 'zh_CN'

# flask_redis
REDIS_URL = 'redis://localhost:6379/0'

# flask_qiniu
QINIU_AK = 'ak'
QINIU_SK = 'sk'
QINIU_PIPELINE = 'pipeline'
QINIU_CALLBACK_URL = 'call back url'
QINIU_PUBLIC_BUCKET_NAME = 'public bucket name'
QINIU_PUBLIC_CDN_DOMAIN = 'public domain name'

QINIU_PRIVATE_BUCKET_NAME = 'private bucket name'
QINIU_PRIVATE_CDN_DOMAIN = 'private domain name'

# flask_jwt
JWT_EXPIRATION_DELTA = timedelta(days=1)


try:
    from .local_config import *
except Exception as e:
    print(e)

youjiao/content/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request, abort
from .models import Activity, Page


content_bp = Blueprint("activity_content", __name__)


@content_bp.route('/activity')
def activity():
    try:
        page = int(request.args.get('page'))
    except Exception as e:
        page = 1
    pagination = Activity.query.filter_by(publish=True).paginate(page, per_page=20)
    weekly_popular_top10 = Activity.weekly_popular_top10()
    return render_template('activity/home.html', activity_list=pagination,
                           category_url=category, current_page='activity', weekly_popular_top10=weekly_popular_top10)


@content_bp.route('/activity/<category>')
def category(category):
    try:
        page = int(request.args.get('page'))
    except Exception as e:
        page = 1

    pagination = Activity.query.filter_by(category=category).filter_by(publish=True).paginate(page, per_page=20)
    category_dict = {
        'policy': u'幼教政策',
        'news': u'幼教新闻',
        'events': u'幼教事件',
        'research': u'理论研究',
        'activity': u'实践活动'
    }
    category_name = category_dict[category]
    weekly_popular_top10 = Activity.weekly_popular_top10()
    return render_template('activity/home.html', activity_list=pagination, category_name=category_name,
                           category_url=category, current_page='activity', sub_page=category, weekly_popular_top10=weekly_popular_top10)


@content_bp.route('/activity/<id>/')
def activity_view(id):
    obj = Activity.query.get(id)
    category_dict = {
        'policy': u'幼教政策',
        'news': u'幼教新闻',
        'events': u'幼教事件',
        'research': u'理论研究',
        'activity': u'实践活动'
    }
    category_name = category_dict[obj.category]
    return render_template('activity/activity.html', activity=obj, category_name=category_name,
                           current_page='activity', obj=obj)


@content_bp.route('/research/home/')
def research_home():
    research_events = Activity.query.filter_by(category='research').filter_by(publish=True).limit(7).all()
    research_result = Activity.query.filter_by(category='achievement').filter_by(publish=True).limit(7).all()
    data = {
        'research_events': research_events,
        'research_result': research_result
    }
    return render_template('research/home.html', data=data, current_page='research')


@content_bp.route('/research/<category>/<page>/')
def research_activity(category, page):
    try:
        page = int(page)
    except ValueError:
        page = 1

    pagination = Activity.query.filter_by(category=category).filter_by(publish=True).paginate(page, per_page=20)
    category_dict = {
        'event': u'教研活动',
        'achievement': u'教研成果'
    }
    category_name = category_dict[category]
    return render_template('research/research_activity.html', category_name=category_name, activity_list=pagination,
                           current_page='research')


@content_bp.route('/research/post/<id>')
def research_post(id):
    obj = Activity.query.get(id)
    category_dict = {
        'researchevents': u'教研活动',
        'researchresult': u'教研成果'
    }
    category_name = category_dict[obj.category]
    return render_template('research/research_activity_content.html', category_name=category_name, activity=obj,
                           current_page='research')


@content_bp.route('/research/teacher/')
def research_teacher():
    return render_template('research/teacher.html', current_page='research')


@content_bp.route('/page/about/')
def page_about():
    return render_template('pages/about.html')


@content_bp.route('/page/<page_title>/')
def pages(page_title):
    content = Page.query.filter_by(title=page_title).first()
    return render_template('pages/tpl.html', content=content, obj=content)

youjiao/onlinecourse/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, abort, render_template
from youjiao.content.models import Slider
from flask_login import current_user
from .models import OnlineCourse
from .permissions import onlinecourse_preview_permission


online_course_bp = Blueprint("online_course", __name__)


@online_course_bp.route('/school/')
def school():
    slider = Slider.onlinecourse_slider()
    return render_template('onlinecourse/home.html', current_page='school',
                           Video=OnlineCourse, slider=slider)


@online_course_bp.route('/video/<int:video_id>')
def video_detail(video_id):
    video = OnlineCourse.query.get_or_404(video_id)
    if not video.publish and not onlinecourse_preview_permission.can():
        abort(404)

    if current_user.is_authenticated:
        video.add_user_visit_recent(current_user)
    return render_template('onlinecourse/video_detail.html', video=video)


@online_course_bp.route('/school/<category>/')
def school_sub(category):
    video_list = OnlineCourse.query.filter(OnlineCourse.publish==True)
    if category == 'lecture':
        video_list = video_list.filter(OnlineCourse.category==u'优秀讲座')
        slider = Slider.onlinecourse_slider()
        return render_template('onlinecourse/sub_node.html', current_page='school',
                               video_list=video_list, slider=slider)
    else:
        abort(404)


@online_course_bp.route('/school/teacher/')
def school_teacher():
    return render_template('onlinecourse/teacher_training.html', current_page='school')


@online_course_bp.route('/school/product/')
def school_product():
    return render_template('onlinecourse/product_training.html', current_page='school')


@online_course_bp.route('/school/product/detail/')
def school_teacher_detail():
    return render_template('onlinecourse/video_detail.html', current_page='school')

youjiao/templates/teaching/__init__.py
__author__ = 'kali'

youjiao/yj_admin/__init__.py
__author__ = 'x'

youjiao/yj_admin/views.py
from youjiao.admin_utils import AuthEditorMixin
from flask_admin import AdminIndexView, expose
from permissions import admin_permission

class YJHomeView(AuthEditorMixin, AdminIndexView):
    @expose()
    def index(self):
        from youjiao.user.models import User, Role
        from youjiao.content.models import Activity, Page
        from youjiao.teach_material.models import Courseware, Book
        from youjiao.onlinecourse.models import OnlineCourse
        from youjiao.yj_media.models import Video, Audio, Document
        from youjiao.photo.models import Photo, Album
        from youjiao.content.models import ContentList
        from youjiao.content.models import Slider
        return self.render('yj_admin/dashboard.html', User=User, Role=Role, Activity=Activity,
                           Courseware=Courseware, Book=Book, Page=Page, OnlineCourse=OnlineCourse,
                           Video=Video, Audio=Audio, Document=Document, Photo=Photo, Album=Album,
                           ContentList=ContentList, Slider=Slider, admin_permission=admin_permission)

youjiao/templates/research/home.html
{% extends "base/base.html" %}

{% block css %}
    <link href="{{ 'research.css' | asset }}" rel="stylesheet">
{% endblock %}

{% block leftBar %}
    {% include 'research/left_bar.html' %}
{% endblock %}

{% block content %}
    <div id="main-big-body">
        <div class="section-block-wrapper">
            <div class="section-block-title-4" style="width: 700px;">名师名园</div>
        </div>
        <ul class="research-home-teachers">
            <li>
                <a href="{{ url_for('activity_content.pages', page_title='humeizhen') }}">
                    <img src="http://7xlydq.com1.z0.glb.clouddn.com/humeizhen.jpg?imageView2/2/w/300">
                </a>
                <h4><a style="color: black;" href="{{ url_for('activity_content.pages', page_title='humeizhen') }}">胡美珍</a></h4>
                <span>著名幼教专家</span>
            </li>
            <li>
                <a href="{{ url_for('activity_content.pages', page_title='jxgbdsyey') }}">
                    <img src="http://7xlydq.com1.z0.glb.clouddn.com/jxgbdsyey.jpg?imageView2/2/w/300">
                </a>
                <h4><a style="color: black;" href="{{ url_for('activity_content.pages', page_title='jxgbdsyey') }}">江西广播电视艺术幼儿园</a></h4>
                <span>省级示范园</span>
            </li>
        </ul>
        <!--<div class="body_content">-->
        <!--<div class="section-block-title-4">教研活动</div>-->
        <!--<ul class="research-home-list">-->
        <!--{% for activity in data.research_events %}-->
            <!--<li>-->
            <!--<a href="{{ url_for('activity_content.research_post', id=activity.id) }}">{{ activity.title }}</a>-->
            <!--<span>[{{ activity.create_time.date() }}]</span>-->
            <!--</li>-->
            <!--{% endfor %}-->
        <!--</ul>-->
        <!--</div>-->
        <div class="research-home-news">
            <div class="section-block-wrapper">
                <div class="section-block-title-4" style="width: 700px;">教研成果</div>
            </div>
            <ul class="news-list">
                {% for activity in data.research_result %}
                    <li>
                        <a href="{{ url_for('activity_content.research_post', id=activity.id) }}">{{ activity.title }}</a>
                        <span class="news-date float-right">[{{ activity.create_time.date() }}]</span>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block rightBar %}
    {% include 'research/home_right_bar.html' %}
{% endblock %}

{% block js %}
    <script src="{{ 'research.js' | asset }}"></script>
{% endblock %}

youjiao/templates/research/home_right_bar.html
<div class="right-bar-small">
    <div class="right-bar-list">
        <!--<ul>-->
            <!--<li class="right-list-first">本月下载排行榜</li>-->
            <!--<li><a href=""><span style="color:orangered">1</span>  有趣的手影</a></li>-->
                 <!--<li><a  href=""><span style="color:orangered">1</span> 有趣的手影</a></li>-->
                 <!--<li><a href=""><span style="color:orangered">1</span>  有趣的手影</a></li>-->
                 <!--<li><a href="">1 有趣的手影</a></li>-->
                 <!--<li><a href="">1 有趣的手影</a></li>-->
                 <!--<li><a href="">1 有趣的手影</a></li>-->
                 <!--<li><a href="">1 有趣的手影</a></li>-->
                 <!--<li><a href="">1 有趣的手影</a></li>-->
                 <!--<li><a href="">1 有趣的手影</a></li>-->
                 <!--<li><a href="">1 有趣的手影</a></li>-->
        <!--</ul>-->
        <ul >
             <li class="right-list-first">课件专题推荐</li>
                 <li style="margin-top:5px;"><a href="">安全教育专题</a></li>
        </ul>
        <div id="right_bar_img">
            <img src="">
            </div>
    </div>
</div>

youjiao/templates/research/left_bar.html
<div class="left-bar">
    <ul class="left-bar-subul-last">
        <li class="left-list-first"><a href="{{ url_for('activity_content.research_home') }}">教学科研</a></li>
        <li><a href="{{ url_for('activity_content.research_teacher') }}">名师名园</a></li>
{#        <li><a href="{{ url_for('activity_content.research_activity', category='event', page=1 ) }}">教研活动</a></li>#}
        <li><a href="{{ url_for('activity_content.research_activity', category='achievement', page=1 ) }}">教研成果</a></li>
    </ul>
{#    <div class="left-adposition">#}
{#        <img src="{{ url_for('static', filename='image/a-d.png') }}" alt="" style="width: 180px;height: 720px;">#}
{#    </div>#}
</div>

youjiao/templates/research/research_activity.html
{% extends "base/base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ 'research.css' | asset }}">
{% endblock %}

{% block leftBar %}
    {% include 'research/left_bar.html' %}
{% endblock %}

{% block content %}
    <div id="main-big-body">
        <div class="e-page-title">教学教研-{{ category_name }}</div>
        <ul class="news-list">
            {% if activity_list.items %}
            {% for activity in activity_list.items %}
                <li>
                    <a href="{{ url_for('activity_content.research_post', id=activity.id) }}">{{ activity.title }} <span
                            class="news-date float-right">[{{ activity.create_time.date() }}]</span></a>
                </li>
            {% endfor %}
            {% else %}
            <h2>内容更新中</h2>
            {% endif %}
        </ul>
        <ul class="activity-pagination">
            {#                        {% if activity_list.has_prev %}#}
            {#                            <li><a class="pagination-first"><<</a></li>#}
            {#                        {% endif %}#}
            {% for page in activity_list.iter_pages() %}
                {% if page %}
                    {% if page != activity_list.page %}
                        <li>
                            <a href="{{ url_for('activity_content.category', category=category_url, page=page) }}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="pagination-active"><a href="javascript:;">{{ page }}</a></li>
                    {% endif %}
                {% else %}
                    <span class=ellipsis>…</span>
                {% endif %}
            {% endfor %}
            {#            {% if activity_list.has_next %}#}
            {#                <li class="pagination-last"></li>#}
            {#            {% endif %}#}
        </ul>
    </div>
{% endblock %}

{% block rightBar %}
    {% include 'research/research_activity_right.html' %}
{% endblock %}

{% block js %}
    <script src="{{ 'research.js' | asset }}"></script>
{% endblock %}

youjiao/templates/research/research_activity_content.html
{% extends "base/base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ 'research.css' | asset }}">
{% endblock %}

{% block leftBar %}
    {% include 'research/left_bar.html' %}
{% endblock %}

{% block content %}
    <div id="main-noright-body">

        <div class="e-page-title">教学教研-{{ category_name }}-{{ activity.title }}</div>
        <div class="activity-content">
            <h2 class="activity-title">{{ activity.title }}</h2>

            <div class="activity-author">
                来源： 中国学前教育研究会 2015年06月20日 作者：admin
            </div>
            <div class="activity-main-content">
                {% autoescape off %}
                {{ activity.html }}
                {% endautoescape %}
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ 'research.js' | asset }}"></script>
{% endblock %}

youjiao/templates/research/research_activity_right.html
<div class="right-bar-small">
    <div class="right-bar-slide">
        <ul class="rslides">
            <li><img src="{{ url_for('static', filename='image/icons/al.jpg') }}" alt="book"></li>
            <li><img src="{{ url_for('static', filename='image/icons/al.jpg') }}" alt="book"></li>
            <li><img src="{{ url_for('static', filename='image/icons/al.jpg') }}" alt="book"></li>
        </ul>
    </div>
    <div class="right-bar-list">
        <ul>
            <li class="right-list-first">最近教研动态</li>
        </ul>
    </div>
    <div class="topics">
        <ul>
            <li class="right-list-first">热点教研活动</li>
        </ul>
    </div>
</div>

youjiao/templates/research/teacher.html
{% extends "base/base.html" %}

{% block css %}
    <link href="{{ 'research.css' | asset }}" rel="stylesheet">
{% endblock %}

{% block leftBar %}
    {% include 'research/left_bar.html' %}
{% endblock %}

{% block content %}
    <div id="main-big-body">
        <div class="e-page-title">教学教研-名师名园</div>
        <div class="research-introduce-switch">
            <a href="#" class="research-tab-s active">名园介绍</a>
            <a href="#" class="research-tab-s">名师风采</a>
        </div>
        <div class="research-introduce-tab">
            <ul class="research-introduce-teachers">
                <li>
                    <a href="{{ url_for('activity_content.pages', page_title='jxgbdsyey') }}">
                        <img src="http://7xlydq.com1.z0.glb.clouddn.com/jxgbdsyey.jpg?imageView2/2/w/300">
                    </a>
                    <div>
                        <h4>
                            <a style="color:black;" href="{{ url_for('activity_content.pages', page_title='jxgbdsyey') }}">江西广播电视艺术幼儿园</a>
                        </h4>
                        <span>江西广播电视艺术幼儿园成立于1999年9月，是一所全面实行0—6岁托幼一体化的早期教育联合机构。</span>
                    </div>
                </li>
            </ul>
        </div>
        <div class="research-introduce-tab display-none">
            <ul class="research-introduce-teachers">
                <li>
                    <a href="{{ url_for('activity_content.pages', page_title='humeizhen') }}">
                        <img src="http://7xlydq.com1.z0.glb.clouddn.com/humeizhen.jpg?imageView2/2/w/300">
                    </a>
                    <div>
                        <h4>
                            <a style="color:black;" href="{{ url_for('activity_content.pages', page_title='humeizhen') }}">胡美珍</a>
                            <span>著名幼教专家</span>
                        </h4>
                        <span>中国学前教育研究委员会委员，前江西学前教育研究会常务副理事长，江西省学前教育学科带头人，江西学前教育教材首席编委、主审，国家“曾宪梓奖’、杰出师范贡献奖获得者</span>
                    </div>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block rightBar %}
    {% include 'research/teacher_right_bar.html' %}
{% endblock %}

{% block js %}
    <script src="{{ 'research.js' | asset }}"></script>
{% endblock %}

youjiao/templates/research/teacher_right_bar.html
<div class="right-bar-small">
    <div class="right-bar-slide">
        <ul class="rslides">
            <li><img src="{{ url_for('static', filename='image/icons/al.jpg') }}" alt="book"></li>
            <li><img src="{{ url_for('static', filename='image/icons/al.jpg') }}" alt="book"></li>
            <li><img src="{{ url_for('static', filename='image/icons/al.jpg') }}" alt="book"></li>
        </ul>
    </div>
    <div class="research-right-hot">
        <h4>热点名园</h4>
        <ul>
            {% for i in range(3) %}
                <li>
{#                    <img src="">#}
{##}
{#                    <div>#}
{#                        <h5>XXX幼儿园</h5>#}
{#                        <h6>ssss</h6>#}
{#                    </div>#}
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="research-right-hot">
        <h4>热点名师</h4>
        <ul>
            {% for i in range(3) %}
                <li>
{#                    <img src="">#}
{#                    <div>#}
{#                        <h5>边霞教授</h5>#}
{#                        <h6>ssss</h6>#}
{#                    </div>#}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>