youjiao/__init__.py
__author__ = 'x'

from .app import create_app

youjiao/app.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from flask_admin import Admin
from flask import Flask, render_template
from flask_wtf import CsrfProtect
from flask_babelex import Babel
from flask_principal import Principal, identity_loaded
from flask_debugtoolbar import DebugToolbarExtension

# from .config import Config
from . import config as youjiao_config
from .user.utils import load_user
from .user.subscribers import connect as user_connect
from .extensions import db, limiter, admin, redis_cli, flask_qiniu, jwt, \
    login_manager
from .utils.csrf import check_csrf

# user
from .user.models import User
from .user.admin import UserAdmin
from .user.utils import _on_identity_loaded
from .user.views import user_bp
from .user.api import user_api_bp

# content
from .content.admin import ActivityAdmin
from .content.models import Activity, Slider, ContentList
from .content.views import content_bp

# book
from .teach_material.admin import BookAdmin
from .teach_material.models import Book, Courseware
from .teach_material.views import book_bp
from .teach_material.api import book_api_bp

# user util
from .user_util.models import Favor
from .user_util.api import user_util_api_bp
from .user_util.admin import LeaveMessageAdmin

# photo
from .photo.models import Photo, Album
from .photo.admin import AlbumAdmin

# yj_media
from .yj_media.admin import VideoAdmin
from .yj_media.models import Video, Audio, Document
from .yj_media.views import media_bp

# online course
from .onlinecourse.models import OnlineCourse
from .onlinecourse.views import online_course_bp
from .onlinecourse.admin import OnlineCourseAdmin

import os
import json


# Flask views
def index():
    # import ipdb; ipdb.set_trace()
    book_content_list = ContentList.query.filter(
        ContentList.position==ContentList.HOME_BOOK).first()
    if book_content_list:
        book_list = book_content_list.obj_list
    else:
        book_list = Book.top10()

    courseware_content_list = ContentList.query.filter(
        ContentList.position==ContentList.HOME_COURSEWARE).first()
    if courseware_content_list:
        courseware_list = courseware_content_list.obj_list
    else:
        courseware_list = Courseware.top10()

    onlinecourse_content_list = ContentList.query.filter(
        ContentList.position==u'首页视频').first()
    if onlinecourse_content_list:
        onlinecourse_list = onlinecourse_content_list.obj_list
    else:
        onlinecourse_list = OnlineCourse.top10()
    return render_template('home/home.html', current_page='home',
                           Book=Book, Courseware=Courseware,
                           slider=Slider.home_slider(),
                           book_list=book_list, courseware_list=courseware_list,
                           onlinecourse_list=onlinecourse_list)


def create_app():
    app = Flask(__name__)
    app.config.from_object(youjiao_config)

    # flask_sqlalchemy
    # import ipdb; ipdb.set_trace()
    db.init_app(app)

    # flask_redis
    redis_cli.init_app(app)



    # flask_debug
    if app.config.get('DEBUG'):
        DebugToolbarExtension(app)

    # flask_login
    login_manager.user_loader(load_user)
    login_manager.login_view = 'user_view.login'
    login_manager.init_app(app)

    # flask_jwt
    jwt.init_app(app)

    # flask_principal
    Principal(app)
    identity_loaded.connect_via(app)(_on_identity_loaded)

    # flask_wtf csrf
    csrf = CsrfProtect()
    csrf.init_app(app)
    app.before_request(check_csrf(csrf))

    # flask_babel
    Babel(app)

    # flask_limiter
    limiter.init_app(app)

    # flask_qiniu
    flask_qiniu.init_app(app)

    # flask_admin
    admin.init_app(app)

    # register blueprint
    app.register_blueprint(content_bp)

    app.register_blueprint(user_bp)

    app.register_blueprint(user_api_bp)

    # import ipdb; ipdb.set_trace()
    app.register_blueprint(book_bp)
    app.register_blueprint(book_api_bp)
    app.register_blueprint(user_util_api_bp)
    app.register_blueprint(media_bp)
    app.register_blueprint(online_course_bp)

    # register subscriber
    user_connect(app)

    # register home page
    app.add_url_rule('/', 'index', index)

    with open(os.path.join(os.getcwd(), 'youjiao/static/assets.json.py'), 'r') as assets:
        app.assets = json.load(assets)

    return app

youjiao/book/views.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from flask import Blueprint, render_template, abort
from youjiao.user_util.models import Comment
from sqlalchemy import and_
from .models import Book

book_bp = Blueprint("book_view", __name__)


@book_bp.route('/book')
def book():
    teach_book_list = Book.query.filter_by(category=u'幼教教材').limit(9)
    read_book_list = Book.query.filter_by(category=u'幼教读物').limit(9)
    # import ipdb; ipdb.set_trace()
    return render_template('book/home.html', teach_book_list=teach_book_list,
                           read_book_list=read_book_list, Book=Book)


@book_bp.route('/book/upload')
def book_upload():
    return render_template('book/upload.html')


@book_bp.route('/book/<category>')
def book_category(category):
    if category == 'teach_book':
        book_list = Book.query.filter_by(category=u'幼教教材').limit(9)
        top10 = Book.top10()
        return render_template('book/sub_node.html', book_list=book_list, top10=top10)

    elif category == 'read_book':
        book_list = Book.query.filter_by(category=u'幼教读物').limit(9)
        return render_template('book/sub_node.html', book_list=book_list)
    else:
        abort(404)


@book_bp.route('/book/<int:book_id>')
def book_detail(book_id):
    book = Book.query.get_or_404(book_id)
    page_comment = Comment.query.filter(
        and_(Comment.comment_obj_type == 'book',
             Comment.comment_obj_id == book.id)).paginate(1)
    return render_template('book/detail.html', book=book,
                           page_comment=page_comment)

youjiao/config/__init__.py
from __future__ import absolute_import
from datetime import timedelta

# Create dummy secrey key so we can use sessions
SECRET_KEY = '123456790'

# DEBUG
DEBUG = True

# Create in-memory database
SQLALCHEMY_DATABASE_URI = 'postgresql://youjiao_db_admin:123@localhost/youjiao_db'
SQLALCHEMY_ECHO = True

# for user register and login security
PASSWORD_HASH = "pbkdf2_sha512"
PASSWORD_SALT = "W0dRBgO0Ukobw8NweLAXvqug2ZTh97HZIEMFcEsWhf7lt68"

# flask_wtf
WTF_CSRF_CHECK_DEFAULT = False

# flask_babel
BABEL_DEFAULT_LOCALE = 'zh_CN'

# flask_redis
REDIS_URL = 'redis://localhost:6379/0'

# flask_qiniu
QINIU_AK = 'ak'
QINIU_SK = 'sk'
QINIU_PIPELINE = 'pipeline'
QINIU_CALLBACK_URL = 'call back url'
QINIU_PUBLIC_BUCKET_NAME = 'public bucket name'
QINIU_PUBLIC_CDN_DOMAIN = 'public domain name'

QINIU_PRIVATE_BUCKET_NAME = 'private bucket name'
QINIU_PRIVATE_CDN_DOMAIN = 'private domain name'

# flask_jwt
JWT_EXPIRATION_DELTA = timedelta(days=1)


try:
    from .local_config import *
except Exception as e:
    print(e)

youjiao/content/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request, abort
from .models import Activity, Page


content_bp = Blueprint("activity_content", __name__)


@content_bp.route('/activity')
def activity():
    try:
        page = int(request.args.get('page'))
    except Exception as e:
        page = 1
    pagination = Activity.query.filter_by(publish=True).paginate(page, per_page=20)
    weekly_popular_top10 = Activity.weekly_popular_top10()
    return render_template('activity/home.html', activity_list=pagination,
                           category_url=category, current_page='activity', weekly_popular_top10=weekly_popular_top10)


@content_bp.route('/activity/<category>')
def category(category):
    try:
        page = int(request.args.get('page'))
    except Exception as e:
        page = 1

    pagination = Activity.query.filter_by(category=category).filter_by(publish=True).paginate(page, per_page=20)
    category_dict = {
        'policy': u'幼教政策',
        'news': u'幼教新闻',
        'events': u'幼教事件',
        'research': u'理论研究',
        'activity': u'实践活动'
    }
    category_name = category_dict[category]
    weekly_popular_top10 = Activity.weekly_popular_top10()
    return render_template('activity/home.html', activity_list=pagination, category_name=category_name,
                           category_url=category, current_page='activity', sub_page=category, weekly_popular_top10=weekly_popular_top10)


@content_bp.route('/activity/<id>/')
def activity_view(id):
    obj = Activity.query.get(id)
    category_dict = {
        'policy': u'幼教政策',
        'news': u'幼教新闻',
        'events': u'幼教事件',
        'research': u'理论研究',
        'activity': u'实践活动'
    }
    category_name = category_dict[obj.category]
    return render_template('activity/activity.html', activity=obj, category_name=category_name,
                           current_page='activity', obj=obj)


@content_bp.route('/research/home/')
def research_home():
    research_events = Activity.query.filter_by(category='research').filter_by(publish=True).limit(7).all()
    research_result = Activity.query.filter_by(category='achievement').filter_by(publish=True).limit(7).all()
    data = {
        'research_events': research_events,
        'research_result': research_result
    }
    return render_template('research/home.html', data=data, current_page='research')


@content_bp.route('/research/<category>/<page>/')
def research_activity(category, page):
    try:
        page = int(page)
    except ValueError:
        page = 1

    pagination = Activity.query.filter_by(category=category).filter_by(publish=True).paginate(page, per_page=20)
    category_dict = {
        'event': u'教研活动',
        'achievement': u'教研成果'
    }
    category_name = category_dict[category]
    return render_template('research/research_activity.html', category_name=category_name, activity_list=pagination,
                           current_page='research')


@content_bp.route('/research/post/<id>')
def research_post(id):
    obj = Activity.query.get(id)
    category_dict = {
        'researchevents': u'教研活动',
        'researchresult': u'教研成果'
    }
    category_name = category_dict[obj.category]
    return render_template('research/research_activity_content.html', category_name=category_name, activity=obj,
                           current_page='research')


@content_bp.route('/research/teacher/')
def research_teacher():
    return render_template('research/teacher.html', current_page='research')


@content_bp.route('/page/about/')
def page_about():
    return render_template('pages/about.html')


@content_bp.route('/page/<page_title>/')
def pages(page_title):
    content = Page.query.filter_by(title=page_title).first()
    return render_template('pages/tpl.html', content=content, obj=content)

youjiao/teach_material/views.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from flask import Blueprint, render_template, abort, request
from flask_login import current_user
from youjiao.user_util.models import Comment
from sqlalchemy import and_, or_
from youjiao.content.models import Slider
from webargs import fields, validate
from webargs.flaskparser import use_args, use_kwargs
from .models import Book, Courseware
from .permissions import book_preview_permission, courseware_preview_permission

book_bp = Blueprint("book_view", __name__)


@book_bp.route('/book')
def book():
    teach_book_list = Book.query.filter(
        and_(Book.category == u'幼教教材', Book.publish == True)).limit(9)
    read_book_list = Book.query.filter_by(category=u'幼教读物').limit(9)
    # import ipdb; ipdb.set_trace()
    return render_template('book/home.html', teach_book_list=teach_book_list,
                           read_book_list=read_book_list, Book=Book,
                           slider=Slider.book_slider())


book_args = {
    'level': fields.Str(missing='', validate=validate.OneOf(Book.level_list+[''])),
    'search': fields.Str(missing='')
}

@book_bp.route('/book/list')
@use_kwargs(book_args)
def book_list(level, search):
    # level = request.args.get('level')
    query = Book.query.filter(Book.publish==True)
    if level:
        query = query.filter(Book.level==level)
    if search:
        query = query.filter(Book.name.like(u'%{}%'.format(search)))
    return render_template('book/list.html', book_list=query, level=level,
                           search=search)


@book_bp.route('/book/<category>')
@use_kwargs({'level': fields.Str(validate=lambda level: level in Book.level_list)})
def book_category(category, level):
    # level = request.args.get('level')
    if category == 'teach_book':
        book_list = Book.query.filter(Book.publish==True, Book.category==u'幼教教材')
        if level:
            book_list = book_list.filter(Book.level==level)
        book_list = book_list.limit(8)
        top10 = Book.top10()
        return render_template('book/sub_node.html', book_list=book_list, top10=top10,
                               level=level, slider=Slider.book_slider(), category=category)

    elif category == 'read_book':
        book_list = Book.query.filter(Book.publish==True, Book.category==u'幼教读物')
        if level:
            book_list = book_list.filter(Book.level==level)
        book_list = book_list.limit(8)
        return render_template('book/sub_node.html', book_list=book_list, level=level,
                               slider=Slider.book_slider(), category=category)
    else:
        abort(404)


@book_bp.route('/book/<int:book_id>')
def book_detail(book_id):
    book = Book.query.get_or_404(book_id)
    if not book.publish and not book_preview_permission.can():
        abort(404)

    if current_user.is_authenticated:
        book.add_user_visit_recent(current_user)

    page_comment = Comment.query.filter(
        and_(Comment.comment_obj_type == 'book',
             Comment.comment_obj_id == book.id)).paginate(1)
    return render_template('book/detail.html', book=book, obj=book,
                           page_comment=page_comment)


@book_bp.route('/book/associate/')
def book_associate():
    return render_template('book/associate.html')


@book_bp.route('/courseware/')
def courseware():
    courseware_list = Courseware.query.limit(12).all()
    return render_template('courseware/home.html', current_page='courseware',
                           courseware_list=courseware_list,
                           Courseware=Courseware, slider=Slider.courseware_slider())


@book_bp.route('/courseware/<int:courseware_id>/')
def courseware_detail(courseware_id):
    courseware = Courseware.query.get(courseware_id)
    if not courseware.publish and not courseware_preview_permission.can():
        abort(404)

    if current_user.is_authenticated:
        courseware.add_user_visit_recent(current_user)

    page_comment = Comment.query.filter(
        and_(Comment.comment_obj_type == 'courseware',
             Comment.comment_obj_id == courseware.id)).paginate(1)
    return render_template('courseware/detail.html', current_page='courseware',
                           courseware=courseware, page_comment=page_comment,
                           obj=courseware)


courseware_args = {
    'level': fields.Str(missing='', validate=validate.OneOf(Courseware.level_list+[''])),
    'search': fields.Str(missing='')
}


@book_bp.route('/courseware/list/')
@use_kwargs(courseware_args)
def courseware_list(level, search):
    # import ipdb; ipdb.set_trace()
    courseware_list = Courseware.query.outerjoin(Book).filter(Courseware.publish==True)
    if search:
        courseware_list = courseware_list.filter(
            or_(Courseware.name.like(u'{}%'.format(search)),
                Book.name.like(u'{}%'.format(search)),
                (Book.name + Courseware.name) == search)
        )
    if level:
        courseware_list = courseware_list.filter(Courseware.level==level)
    courseware_list = courseware_list.all()
    return render_template('courseware/list.html', current_page='courseware',
                           courseware_list=courseware_list, level=level,
                           search=search)


@book_bp.route('/courseware/sub/')
@use_args(courseware_args)
def courseware_sub(args):
    top10 = Courseware.top10()
    level = args.get('level')
    if not level:
        courseware_list = Courseware.query.limit(10).all()
    elif level in [u'小班', u'中班', u'大班']:
        courseware_list = Courseware.query.join(Book).filter(Book.level == level).all()
    else:
        courseware_list = []
    return render_template('courseware/sub_node.html', current_page='courseware',
                           top10=top10, courseware_list=courseware_list,
                           slider=Slider.courseware_slider())


from youjiao.flask_qiniu import get_private_url


@book_bp.app_template_filter('qiniu_private_url')
def qiniu_private_url(key):
    return get_private_url(key)

youjiao/templates/teaching/__init__.py
__author__ = 'kali'

youjiao/yj_admin/__init__.py
__author__ = 'x'

youjiao/templates/courseware/detail.html
{% extends "base/base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ 'courseware.detail.css' | asset }}">
    <link rel="stylesheet" href="{{ 'vendor/video-js/video-js.min.css' | vendor_asset }}">
{% endblock %}

{% block leftBar %}
    {% include 'courseware/left_bar.html' %}
{% endblock %}

{% block content %}
    <div id="main-noright-body">

        <div class="e-page-title">课件中心-教材配套课件-{{ courseware.book.level }}-{{ courseware.name }}</div>

        <div>
            <div class="product-container">
                <div class="samples-imgs">
                    <img src="{{ '%s?imageView2/2/w/300'|format(courseware.cover) }}" alt=""
                         style="width: 484px;height: 460px;background: #CCCCCC;">
                </div>
                <div class="product-info">
                    <div class="product-title">
                        <h3>{{ courseware.book.name }}</h3><span>{{ courseware.book.level }}</span>
                    </div>
                    <table>
                        <tr>
                            <td class="product-info-detail">课程内容：</td>
                            <td>{{ courseware.name or ''}}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="product-detail-comments">
                <div class="detail-comment-title">
                    <a href="javascript:;" class="book-switch active">课件详情</a>
                    {#                    <a href="javascript:;" class="book-switch">课件评论</a>#}
                </div>
                <div>
                    <p class="detail-comment-content courseware-detail-content">

                        {% if current_user.is_authenticated and current_user.can_view_vip_content %}

                            {% for document in courseware.document_list %}
                                <div class="document-img">
                                    {% for img in document.img_list %}
                                        <img src="{{ img | qiniu_private_url }}" alt=""
                                             {% if loop.index==1 %}class="document-img-first"{% endif %}>
                                    {% endfor %}
                                    <span>{{ document.name }}</span>
                                </div>
                            {% endfor %}

                            {% for video in courseware.video_list %}
                                <div class="video-detail-course">
                                    <video id="video-detail-c" class="video-js vjs-default-skin" controls
                                           preload="auto"
                                           width="760"
                                           height="400" data-setup='{}'>
                                        <source src='{{ video.key| qiniu_private_url }}' type='video/mp4'/>
                                    </video>
                                    <p>视频： {{ video.name }}</p>
                                </div>
                            {% endfor %}

                            {% if courseware.audio_list| length > 0 %}
                                <audio preload></audio>
                                {% for audio in courseware.audio_list %}
                                    <div class="audio-list">
                                        <p><a href="javascript:;"
                                              data-src="{{ audio.key | qiniu_private_url }}">{{ audio.name }}</a></p>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% elif current_user.is_authenticated %}
                            <p>需要成为VIP会员后才能观看</p>
                        {% else %}
                            <p>请登陆并成为VIP会员后观看</p>
                        {% endif %}
                </div>
                <div class="detail-comment-content display-none">
                    <ul id="book-content-list">
                        {% for comment in page_comment.items %}
                            <li>
                                <div>
                                    <img src="{{ comment.user.avatar }}" alt="">
                                    <h6>{{ comment.user.nickname or comment.user.name }}</h6>
                                </div>
                                <span>{{ comment.content }}</span>
                            </li>
                        {% endfor %}
                    </ul>
                    <ul class="comment-pagination">
                        <li>
                            <a href="#">1</a>
                        </li>
                    </ul>
                        <textarea name="" id="comment-textarea" {% if not current_user.is_authenticated %}
                                  disabled {% endif %}>

                        </textarea>
                    <a href="javascript:;"
                            {% if current_user.is_authenticated %} id='book-publish-comment' {% endif %}
                       class="book-publish-comment">发布</a>
                </div>
            </div>

        </div>
        {% if courseware.related_courseware %}
            <div class="other-associate-courseware">
                <p>其他课件相关</p>
                {% for courseware in courseware.related_courseware %}
                    <a href="{{ courseware.link }}">
                        <div>
                            <img src="{{ courseware.cover }}" alt="">

                            <p>{{ courseware.name }}</p>
                        </div>
                    </a>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ 'vendor/audiojs/audio.min.js' | vendor_asset }}"></script>
    <script>
        $(function () {
            var as = audiojs.createAll();
            var audio = as[0];
            audio.load($('.audio-list p').children('a').attr('data-src'));
            $('.audio-list p').click(function (e) {
                e.preventDefault();
                $('.audiojs').css('display', 'block');
                audio.load($('a', this).attr('data-src'));
                audio.play();
                $('.audio-playing').removeClass('audio-playing');
                $(this).addClass('audio-playing');
            });
        });
    </script>
    <script src="{{ 'vendor/video-js/video.js' | vendor_asset }}"></script>
    <!--[if lt IE 9]>
    <script src="{{ 'vendor/video-js/videojs-ie8.min.js'| vendor_asset }}"></script>
    <![endif]-->
    <script src="{{ 'courseware.detail.js' | asset }}"></script>
{% endblock %}

youjiao/templates/courseware/home.html
{% extends "base/base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ 'courseware.home.css' | asset }}">
{% endblock %}

{% block leftBar %}
    {% include 'courseware/left_bar.html' %}
{% endblock %}

{% block content %}
    <div id="main-big-body">
        <div class="courseware-slides">
            <div class="courseware-slides-main">
                <ul class="rslides">
                    {% for img_link in slider %}
                    <li>
                        <a href="{{ img_link.link }}">
                        <img src="{{ img_link.image }}" alt="banner">
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="video-section-b">
            <div class="section-block-wrapper">
                <div class="section-block-title-6" style="width:700px">教材配套课件</div>
            </div>
            <ul class="video-section-list">
                {% for courseware in courseware_list %}
                    <li>
                        <a href="{{ courseware.link }}">
                            <div class="v-image-wrapper">
                                <img src="{{ '%s?imageView2/2/w/600'|format(courseware.cover) }}" alt="">

                                <div class="v-image-hover-layer">
                                    <div class="v-hover-layer-icon"></div>
                                </div>
                            </div>
                            <h5>{{ courseware.name }}</h5>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <!--<div class="video-section-b">-->
            <!--<div class="section-block-wrapper">-->
                <!--<div class="section-block-title-6">其他课件资源</div>-->
            <!--</div>-->
            <!--<ul class="video-section-list">-->
                <!--{% for i in range(6) %}-->
                    <!--<li>-->
                        <!--<a href="/courseware/detail/">-->
                            <!--<div class="v-image-wrapper">-->
                                <!--<img src="{{ url_for('static', filename='image/icons/qinghua.png') }}" alt="">-->

                                <!--<div class="v-image-hover-layer">-->
                                    <!--<div class="v-hover-layer-icon"></div>-->
                                <!--</div>-->
                            <!--</div>-->
                            <!--<h5>青花瓷</h5>-->
                            <!--<a href="" class="start-download">开始下载</a>-->
                        <!--</a>-->
                    <!--</li>-->
                <!--{% endfor %}-->
            <!--</ul>-->
        <!--</div>-->
    </div>
{% endblock %}

{% block rightBar %}
    {% include 'courseware/right_bar.html' %}
{% endblock %}

{% block js %}
       <script src="{{ 'courseware.home.js' | asset }}"></script>
{% endblock %}

youjiao/templates/courseware/left_bar.html
<div class="left-bar">
    <ul class="left-bar-subul-last">
        <li class="left-list-first"><a href="{{ url_for('book_view.courseware_list') }}">课件中心</a></li>
        <li><a href="{{ url_for('book_view.courseware_sub') }}">教材配套课件</a></li>
        <!--<li><a href="{{ url_for('book_view.courseware_sub') }}">其他课件资源</a></li>-->
    </ul>
{#    <div class="left-adposition">#}
{#        <img src="{{ url_for('static', filename='image/a-d.png') }}" alt="" style="width: 180px;height: 720px;">#}
{#    </div>#}
</div>

youjiao/templates/courseware/list.html
{% extends "base/base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ 'courseware.list.css' | asset }}">
{% endblock %}

{% block leftBar %}
{% include 'courseware/left_bar.html' %}
{% endblock %}

{% block content %}
<div id="main-school-body">
    <div class="e-page-title">课件中心-教材配套课件-{{level or '全部课件'}}</div>
    <div class="video-section-lg">
        <h3 style="text-align: center;line-height: 40px;">{{ level or '全部' }}课件</h3>
        <div class="search-input">
            <a class="search-button" href="javascript:;" id="search-button">
                <img src="{{ url_for('static', filename='image/icons/iconfont-search.png') }}"
                     style="width: 18px;height: 18px;margin-top: 6px;" alt="">
            </a>
            <input id="search-input" type="text" value="{{search}}">
        </div>
        <div class="section-block-wrapper">
            <div class="section-block-title-4">班级分类</div>
            <div class="classes-select-wrapper">
                <select name="" id="" class="classes-select">
                    <option value="" {% if not level %}selected="selected"
                            {% endif %}>全部</option>
                    <option value="幼小衔接班" {% if level=="幼小衔接班" %}
                            selected="selected" {% endif %}>幼小衔接班</option>
                    <option value="大班" {% if level=="大班" %}
                            selected="selected" {% endif %}>大班</option>
                    <option value="中班" {% if level=="中班" %}
                            selected="selected" {% endif %}>中班</option>
                    <option value="小班" {% if level=="小班" %}
                            selected="selected" {% endif %}>小班</option>
                </select>
            </div>
        </div>
        <ul class="video-section-list">
            {% for courseware in courseware_list %}
            <li>
                <a href="{{ courseware.link }}">
                    <div class="v-image-wrapper">
                        <img src="{{ '%s?imageView2/2/w/600'|format(courseware.cover) }}" alt="">

                        <div class="v-image-hover-layer">
                            <div class="v-hover-layer-icon"></div>
                        </div>
                    </div>
                    <h5>{{ courseware.name }}</h5>
                </a>
            </li>
            {% else %}
            <h1>相关内容即将上线，敬请期待！</h1>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{{ 'courseware.list.js' | asset }}"></script>
{% endblock %}

youjiao/templates/courseware/product_training.html
{% extends "base/base.html" %}

{% block leftBar %}
    {% include 'school/left_bar.html' %}
{% endblock %}

{% block content %}
    <div id="main-school-body">
        <div class="e-page-title">幼教网校-产品使用培训</div>
        <div class="video-section-lg">
            <h3 style="text-align: center;line-height: 40px;">产品使用培训</h3>
            <ul class="video-section-list">
                {% for i in range(12) %}
                    <li>
                        <div class="v-image-wrapper">
                            <img src="{{ url_for('static', filename='image/icons/qinghua.png') }}" alt="">

                            <div class="v-image-hover-layer"></div>
                        </div>
                        <h5>青花瓷</h5>
                        <a href="" class="start-download">开始下载</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='vendor/js/responsiveslides.js') }}"></script>
    <script src="{{ url_for('static', filename='build/js/youjiao.js') }}"></script>
{% endblock %}

youjiao/templates/courseware/right_bar.html
<div class="right-bar-small">
    <div class="right-bar-list">
        <ul>
            <li class="right-list-first">本月下载排行榜</li>
            {% for courseware in Courseware.top10() %}
            <li><a href="{{ courseware.link }}">{{ loop.index }}.{{ courseware.name or '' }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="topics">
        <ul>
            <li class="right-list-first">课件专题推荐</li>
        </ul>
    </div>
</div>